# -*- coding: utf-8 -*-
"""DLExperiment_08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MwwTJ29QytX9T1yIa0w4mqtmvF1A4FxL
"""

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

from lime import lime_image
from skimage.segmentation import mark_boundaries

(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Normalize (0–1 scaling)
x_train = x_train / 255.0
x_test = x_test / 255.0

# Reshape for CNN: (28, 28, 1)
x_train = x_train.reshape(-1, 28, 28, 1)
x_test = x_test.reshape(-1, 28, 28, 1)

print("Train shape:", x_train.shape)
print("Test shape:", x_test.shape)

model = keras.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(10, activation='softmax')   # 10 classes (0–9)
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    x_train, y_train,
    epochs=3,
    validation_data=(x_test, y_test)
)

loss, acc = model.evaluate(x_test, y_test)
print("Test Accuracy:", acc)

explainer = lime_image.LimeImageExplainer()

index = 15
image = x_test[index]

plt.imshow(image.squeeze(), cmap='gray')
plt.title(f"True Label: {y_test[index]}")
plt.axis('off')
plt.show()

def predict_fn(images):
    images = images.astype('float32')

    # convert RGB → grayscale (take mean across channels)
    if images.shape[-1] == 3:
        images = np.mean(images, axis=-1, keepdims=True)

    return model.predict(images)

explanation = explainer.explain_instance(
    image.squeeze(),
    classifier_fn=predict_fn,
    top_labels=5,
    hide_color=0,
    num_samples=1000,
    random_seed=42
)

temp, mask = explanation.get_image_and_mask(
    explanation.top_labels[0],
    positive_only=True,
    num_features=10,
    hide_rest=False
)

plt.imshow(mark_boundaries(temp, mask))
plt.title("LIME Explanation (Important Pixels)")
plt.axis('off')
plt.show()